Fix LDAP connection with AD when idling
Periodically, the LDAP connection with an AD throws an error, due to
idling:
```
Error: read ECONNRESET
  at exports._errnoException (util.js:1020:11)
  at TCP.onread (net.js:568:26)
```